- packages/reg-suit-cli/src/commands/init.ts
- packages/reg-suit-core/src/config-manager.ts
- packages/reg-suit-core/src/core.ts
- packages/reg-suit-core/src/processor.ts
- packages/reg-suit-util/src/fs-util.ts
> [#21] fix workingDir

- package.json
- packages/reg-publish-s3-plugin/README.md
- packages/reg-publish-s3-plugin/src/s3-bucket-preparer.ts
- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
- packages/reg-suit-util/src/logger.ts
> Enhancement s3 preparer

- packages/reg-publish-s3-plugin/e2e/script.ts
- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
- packages/reg-suit-cli/src/commands/init.ts
- packages/reg-suit-cli/src/commands/prepare.ts
- packages/reg-suit-cli/src/commands/run.ts
- packages/reg-suit-core/package.json
- packages/reg-suit-core/src/config-manager.test.ts
- packages/reg-suit-core/src/config-manager.ts
- packages/reg-suit-core/src/core.ts
- packages/reg-suit-core/src/plugin-manager.test.ts
- packages/reg-suit-core/src/plugin-manager.ts
- packages/reg-suit-core/src/processor.ts
- packages/reg-suit-core/yarn.lock
- packages/reg-suit-interface/src/core.ts
- packages/reg-suit-interface/src/plugin.ts
> Enhancement core params

- packages/reg-suit-core/package.json
- packages/reg-suit-core/yarn.lock
> use latest reg-cli

- packages/reg-keygen-git-hash-plugin/README.md
- packages/reg-keygen-git-hash-plugin/src/commit-explorer.ts
- packages/reg-keygen-git-hash-plugin/src/index.ts
> Add fixed rev option

- packages/reg-suit-util/src/logger.ts
> [#53] explicit setting level

- packages/reg-notify-github-plugin/src/github-notifier-plugin.ts
- packages/reg-notify-slack-plugin/src/slack-notifier-plugin.ts
- packages/reg-publish-s3-plugin/src/s3-bucket-preparer.ts
- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
- packages/reg-suit-cli/src/commands/install.ts
- packages/reg-suit-core/src/processor.ts
- packages/reg-suit-interface/src/logger.ts
- packages/reg-suit-util/package.json
- packages/reg-suit-util/src/logger.ts
- packages/reg-suit-util/yarn.lock
> Spin progress

- packages/reg-suit-cli/package.json
- packages/reg-suit-cli/src/package-util.ts
- packages/reg-suit-cli/src/tsconfig.json
- packages/reg-suit-cli/yarn.lock
- packages/reg-suit-core/package.json
- packages/reg-suit-core/src/plugin-manager.test.ts
- packages/reg-suit-core/src/plugin-manager.ts
- packages/reg-suit-core/yarn.lock
> Remove resolve

- README.md
Modify TravisCI workaround in readme.
Do you need more explanation on this?
> Modify CI workaround in readme.

- packages/reg-suit-toppage/capture.js
- packages/reg-suit-toppage/public/index.html
- packages/reg-suit-toppage/public/styles/index.scss
> [#51] modify scss

- packages/reg-suit-core/package.json
- packages/reg-suit-core/yarn.lock
> Use reg-cli v0.8.8

- packages/reg-keygen-git-hash-plugin/src/commit-explorer.ts
- packages/reg-keygen-git-hash-plugin/src/git-cmd-client.ts
- packages/reg-keygen-git-hash-plugin/test/builder/commit-new-branch.sh
- Remove `git show-branch` command.
- Improve performance.
Relevant issue: #84 
I guessed this issue caused by performance.
Therefore, I would like to see how it goes by this fixes.
> Drop show-branch

- packages/reg-suit-core/package.json
- yarn.lock
Could you please use latest reg-cli.
> upgrade reg-cli

- package.json
- packages/reg-gh-app-front/package.json
- packages/reg-gh-app-interface/package.json
- packages/reg-gh-app/package.json
- packages/reg-keygen-git-hash-plugin/package.json
- packages/reg-keygen-git-hash-plugin/src/index.ts
- packages/reg-notify-github-plugin/package.json
- packages/reg-notify-slack-plugin/package.json
- packages/reg-publish-s3-plugin/package.json
- packages/reg-publish-s3-plugin/src/s3-bucket-preparer.ts
- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
- packages/reg-simple-keygen-plugin/package.json
- packages/reg-suit-cli/package.json
- packages/reg-suit-core-testing/package.json
- packages/reg-suit-core/package.json
- packages/reg-suit-core/src/core.ts
- packages/reg-suit-core/src/processor.ts
- packages/reg-suit-interface/package.json
- packages/reg-suit-interface/src/plugin.ts
- packages/reg-suit-util/package.json
- yarn.lock
> [#93] update typescript version

- packages/reg-suit-cli/src/cli.ts
> Fix bug that `publish` command not notify even if specify `-n` or `--notification`

- packages/reg-suit-cli/package.json
- packages/reg-suit-cli/src/commands/prepare.ts
- packages/reg-suit-core/src/core.ts
- yarn.lock
> Add ask into preparing core

- README.md
- packages/reg-suit-cli/src/commands/prepare.ts
- packages/reg-suit-core/package.json
- packages/reg-suit-core/src/processor.ts
- packages/reg-suit-interface/src/core.ts
- yarn.lock
> add alternative threshold options via #103

- packages/reg-notify-slack-plugin/src/send-web-hook.ts
- packages/reg-notify-slack-plugin/src/slack-notifier-plugin.ts
- packages/reg-notify-slack-plugin/src/slack-preparer.ts
* if changed, slack notify danger color (red)
* if added/removed, slack notify warning color (yellow)
* if passed only, slack notify good color (green)
> add status color to slack notifier

- packages/reg-publish-gcs-plugin/package.json
- packages/reg-publish-gcs-plugin/src/gcs-publisher-plugin.ts
- packages/reg-publish-gcs-plugin/src/tsconfig.json
- packages/reg-publish-s3-plugin/package.json
- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
- packages/reg-publish-s3-plugin/src/tsconfig.json
- packages/reg-suit-util/package.json
- packages/reg-suit-util/src/cloud-storage-util.ts
- packages/reg-suit-util/src/index.ts
- yarn.lock
> extract abs class from gcs plugin

- packages/reg-notify-gitlab-plugin/src/create-comment.ts
Missing spaces are messing the display
fix: #123
> fix: add missing space in comment

- packages/reg-suit-toppage/package.json
- packages/reg-suit-toppage/regconfig.json
Configure slack notification to reg-viz-jp slack workspace
> configure slack plugin

- packages/reg-suit-core/src/processor.ts
> Fix typo in core processer log message

- README.md
- packages/reg-suit-core/src/processor.ts
- packages/reg-suit-interface/src/core.ts
ref: https://github.com/reg-viz/reg-cli/pull/204
> Add matchingThreshold config

- packages/reg-gh-app/src/pr-comment-fns.ts
I noticed that the copy on the PR comment has some minor grammar issues,
so I figured I'd help out by tweaking the sentences a bit.
> Minor copy improvements in PR comment

- packages/reg-suit-core/package.json
- yarn.lock
> chore: upgrade reg-cli to 0.15.2

- packages/reg-suit-core/package.json
- yarn.lock
> chore: reg-cli 0.15.7

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
I added Issue and Pull Request templates.
We expect users to contribute in a unified format :memo:
> docs: Add GitHub Issue & Pull Request templates

- packages/reg-suit-core/package.json
- yarn.lock
See https://github.com/reg-viz/reg-cli/pull/286 and https://github.com/reg-viz/reg-cli-report-ui/pull/23
https://github.com/reg-viz/reg-cli-report-ui/pull/23
> chore: upgrade reg-cli

- packages/reg-suit-core/package.json
- yarn.lock
ref #163 
fix ignore files to publish sample dir.
#163
> fix: upgrade cli

- packages/reg-suit-core/package.json
- yarn.lock
> chore: update cli

- packages/reg-publish-gcs-plugin/README.md
- packages/reg-publish-gcs-plugin/src/gcs-publisher-plugin.ts
Add `customUri` option to GCS plugin.
> feat: add customUri option to GCS plugin

- packages/reg-notify-github-with-api-plugin/.gitignore
- packages/reg-notify-github-with-api-plugin/.npmignore
- packages/reg-notify-github-with-api-plugin/README.md
- packages/reg-notify-github-with-api-plugin/package.json
- packages/reg-notify-github-with-api-plugin/src/create-comment.ts
- packages/reg-notify-github-with-api-plugin/src/gh-api-notifier-plugin.ts
- packages/reg-notify-github-with-api-plugin/src/gh-api-preparer.ts
- packages/reg-notify-github-with-api-plugin/src/gh-gql-client.ts
- packages/reg-notify-github-with-api-plugin/src/index.ts
- packages/reg-notify-github-with-api-plugin/src/tsconfig.build.json
- packages/reg-notify-github-with-api-plugin/src/tsconfig.json
- packages/reg-suit-cli/well-known-plugins.json
- yarn.lock
> feat: Add notify plugin for GHE

- README.md
- packages/reg-notify-github-with-api-plugin/src/index.ts
> Fix ghapi plugin preparerer

- packages/reg-publish-gcs-plugin/README.md
fix typo in reg-publish-gcs-plugin/README.md
> fix typo in reg-publish-gcs-plugin/README.md

- README.md
https://github.com/tadashi-aikawa/owlora now uses Puppeteer instead of Loki for capturing screenshots.
README example description.
- https://github.com/tadashi-aikawa/owlora/blob/032ceccc6a/storybook-camera.js#L21
> Change example description

- README.md
Since an error occurred in the setting of GitHub Actions of the readme, I propose a fix.
> Fix GitHub Actions config error

- README.md
Improve README about GitHub Actions settings.
- #186 
No screenshots
After merged https://github.com/reg-viz/reg-simple-demo/pull/31 and the workflow succeeded.
> add readme for Github Actions checkout option

- packages/reg-keygen-git-hash-plugin/src/index.ts
Fixes an error message with correct grammar.
n/a
n/a
n/a
> Fix grammar in an error message

- README.md
Fixes  grammar issue in the readme
> Fix grammar issue in readme

- packages/reg-suit-core/package.json
- yarn.lock
See https://github.com/reg-viz/reg-cli-report-ui/pull/32
https://github.com/reg-viz/reg-cli-report-ui/pull/32
NA
NA
> fix: Upgrade reg-cli

- .circleci/config.yml
> chore: Add auth to pull image

- packages/reg-suit-core/src/processor.ts
> fix(core): Explicitly pass 0 as threshold for PM

- README.md
Update readme: add info about reg-notify-chatwork-plugin
> Update readme: reg-notify-chatwork-plugin

- packages/reg-notify-github-plugin/package.json
- yarn.lock
> chore: Bump reg-gh-app interface

- .circleci/config.yml
- .github/workflows/build.yml
- packages/reg-publish-s3-plugin/package.json
> chore: bump up base image version

- .github/workflows/build.yml
> chore: Configure branch condition

- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
> fix(s3-plugin): Use transformToByteArray rather than transformToString

- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
fixes #677. `ListObjectsV2Command` is called with `Marker` parameter, but `ListObjectsV2Command` does not support it. We should use `ContinuationToken` instead.
- #677
- https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-s3/Interface/ListObjectsV2CommandInput/
1. Prepare an environment that has more than 1000 objects in a S3 bucket
2. Run reg-suit with reg-publish-s3-plugin
> fix(s3-plugin): Use ContinuationToken to get all objects recursively

- packages/reg-suit-core/package.json
- yarn.lock
- upgrade `reg-cli` to 0.18.5
- https://github.com/reg-viz/reg-cli/pull/490
NA
> Upgrade reg cli 0.18.5
