reg-viz/reg-suit

- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
`https://s3.amazonaws.com/bucket` is only applicable to the default, US East (N. Virginia) region.
When using a bucket created in another region (e.g. `export AWS_REGION=eu-west-1` or by using a profile), clicking on the report link will result in following error:
```xml
<Error>
<Code>PermanentRedirect</Code>
<Message>
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
</Message>
<Bucket>mymaths-player-visreg</Bucket>
<Endpoint>mymaths-player-visreg.s3.amazonaws.com</Endpoint>
<RequestId>BBB688EBF6359B85</RequestId>
<HostId>
qGm+crinY/ipeRB5YP8m2KfrKYX2ISHFp7Jl0oVI8QtdDsGfd3qso9UDvjqa2b5CCmXBsLuyJ/0=
</HostId>
</Error>
```
> Teach reportUrl to respect AWS Region Endpoints

- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
I can not see the report in the displayed URL.I guess that I used an existing `ap-northeast-1` region bucket without using `s3-bucket-preparer`.
Display `https://s3-ap-northeast-1.amazonaws.com/[MY_BUCKET_NAME]/COMMIT_HASH/index.html`(path-style) or 
`https:///[MY_BUCKET_NAME].s3.amazonaws.com/COMMIT_HASH/index.html`(hosted-style)
Display `https://s3.amazonaws.com/[MY_BUCKET_NAME]/COMMIT_HASH/index.html`
If using US standard (US West (N. California)) region, we can access to report by following endpoint.
`https://s3.amazonaws.com/[MY_BUCKET_NAME]//COMMIT_HASH/index.html`
However we use other region, we can not access report.Therefore we should probably use `hosted-style` or `path-style` endpoint.
I think `hosted-style` is better than `path-style`, because it does not have to know bucket …
> Modify report url to hosted-style endpoint.

- README.md
- package.json
- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
- packages/reg-suit-cli/src/commands/prepare.ts
- packages/reg-suit-core/package.json
- packages/reg-suit-core/src/processor.ts
- packages/reg-suit-interface/src/core.ts
- yarn.lock
A part work of https://github.com/reg-viz/reg-cli/issues/90 .
>  Hoist the above option to reg-suit/core option. User can set this using regconfig.json
I introduce `ximgdiff` option to `core` config, and set the invocation type value `client`. 
But this option is extremely experimental. So If you prefer turning it off by default, I change it so.
And I modify S3 plugin:
- publish `.js` and `.wasm` too
- upload/download using `ContentEncoding: gzip` header. Because it's too slow to download no-compressed WASM file from S3...
> Additional engine

- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
Hi!
I use reg-suit in my products and a company, thank you 😄 
However we can't publish report whose ACL is `public-read`.
So I am glad if we enable to specify `private` to `acl` property in config like..
```
"reg-publish-s3-plugin": {
"bucketName": "sample-bucket",
"acl": "private"
}
```
Best regards.
> Enable to specify ACL

- packages/reg-suit-interface/package.json
`reg-suit-interface` exports `lib/plugin.d.ts`, which references `inquirer`. Since `inquirer` is a dev dependency, though, TypeScript chokes on the reference, because `@types/inquirer` isn't installed in libraries that depend on `reg-suit-interface`.
> Make `@types/inquirer` a regular dependency

- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
- packages/reg-suit-core/src/processor.ts
Hi :) I want to use `Credentials from Instance Metadata` in EC2 instance.(please see. https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html#instance-metadata-security-credentials). In this case, credentials are automatically obtained from  EC2 instance metadata service via `aws-sdk`.
However, when using this way, `_checkCredential` will fail in the current version. So, I think that it is better to delegate authentication processing to `aws-sdk`package.
Do you have any thoughts?
> Remove checkCredential to get credentials from EC2 instance metadata service

- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
Hi, thank you for your great projects. reg-suit is very easy to use and a nice tool for visual regression testing.
I used reg-suit for web services with more than 1,000 pages. 
Then, I found the following behavior (maybe bug) about  S3 listObject pagination.
This PR is the fix of the behavior.
- Given that the number of screenshots are more than 1,000.
- We can upload them (publish) to S3 with no problem.
- But, we can download only 1,000 screenshots in the next comparison. 
Logs
```
// Actual snapshot directory has 1011 items. (keys are shadowed.)
1011
// But, we can download only 1,00 items with sync-expected.
[reg-suit] info version: 0.7.2
[reg-suit] info Detected the previous snapshot key: 'yyy'
■ 0% | ETA: 0s | 0/1000[reg-publish-s3-plugin] info Download 1000 files from …
```
> Support for large number of screenshots (> 1,000) in reg-publish-s3-plugin.

- packages/reg-suit-core/src/config-manager.test.ts
- packages/reg-suit-core/src/config-manager.ts
I want to inject env var to core conf as well.
Is there any reason to restrict this feature for only plugins?
> Replace env vars for core conf

- packages/reg-suit-core/src/config-manager.ts
I got the following config when I ran `reg-suit prepare` with no plugins:
```
$ reg-suit prepare
[reg-suit] info version: 0.7.15
[reg-suit] info Configuration:
[reg-suit] info {
"core": {
"workingDir": ".reg",
"actualDir": "directory_contains_actual_images",
"threshold": 0
},
"plugins": {}
}
```
I was confused what "core.threshold" is because it was replaced with "core.thresholdRate"
and there's no documentation for that.
https://github.com/reg-viz/reg-suit/pull/104
I guess threshold is deprecated so let's change default config.
----
I can't find the way to test for this behavior.
I hope it works but to be honest I'm not sure.
> Change default config

- packages/reg-publish-s3-plugin/README.md
- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
Hi all. First of all, thank you very much for this awesome and exciting project. I'm really looking forward to use this in my daily workflow.
I wondered whether to just open an issue or create a PR but have decided to create a PR because I've tested the following change locally.
Added ability to inject sdk options into the S3 client via regconfig.json.
Currently, the S3 client is created without any sdk options, hence custom configs cannot be injected. Generally this probably isn't a problem, but I've wanted to test the functionality with [minio](https://github.com/minio/minio), a S3 API compatible object storage server. In order for this to work, I need to inject the following options to the S3 client.
```json
{
"endpoint": "<THE ENDPOINT TO THE MINIO SERVER>",
"s3ForcePathStyle": true, …
```
> Add sdkOptions to s3-publisher-plugin

- packages/reg-notify-github-plugin/package.json
- packages/reg-notify-github-plugin/src/github-preparer.ts
- yarn.lock
Opn is safer and actively maintained. Also, `npm/yarn audit` marks `open` as a critical vulnerability.
> Use opn over open

- package.json
- packages/reg-publish-gcs-plugin/e2e/script.ts
- packages/reg-publish-gcs-plugin/package.json
- packages/reg-publish-gcs-plugin/src/gcs-bucket-preparer.ts
- packages/reg-publish-gcs-plugin/src/gcs-publisher-plugin.ts
- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
- packages/reg-suit-util/src/cloud-storage-util.ts
- yarn.lock
This PR contains following changes:
- fixed `reg-publish-gcs-plugin`'s nextPageToken bug (described below)
- by sending [nextPageToken](https://cloud.google.com/storage/docs/json_api/v1/objects/list) instead of file's `key`
- to retrieve `nextPageToken`, bumped version of `@google-cloud/storage` to latest
- bumped version of `@google-cloud/storage`'s dependencies (`typescript`, `@types/node`)
1. prepare more than the paging limit(1000) images
2. publish the images to GCS bucket
3. run `reg-suit sync-expected`
Here's my error log:
```
[reg-suit] info version: 0.7.17
[reg-suit] info Detected the previous snapshot key: '................'
{ ApiError: Invalid Value
at Object.parseHttpRespBody (/root/web/node_modules/@google-cloud/common/src/util.js:193:30)
at Object.handleResp …
```
> Fix GCS nextPageToken bug

- packages/reg-notify-gitlab-plugin/src/create-comment.ts
reg-notify-gitlab-plugin generated broken visual comments.
see #123
> fix: add missing spaces between emojis

- packages/reg-suit-util/src/cloud-storage-util.ts
Thanks for such a cool tool! I have met an issue while trying to use this tool. I'm happy if you could see this change 😊
While publishing files, this tool tries to upload directories under the hard-to-happen condition. That is the case when a directory ends in file extension like `.js`, `.html`, `wasm`, and so on. It happens because files are listed by [`node-glob`](https://github.com/isaacs/node-glob) by **a bit looser** condition like the example below (this is not a complete copy of the existing code, though)
```
glob("**/*.{html,js,wasm,png,json,jpeg,jpg,tiff,bmp,gif}", {
cwd: this.getWorkingDirs().base,
}, ...
```
Under this condition, directories that have the name with file extension can be listed. As a result, file uploading would fail.
It's easy to fix it because `node-glob` has …
> fix: stop uploading directories by passing nodir=true to glob

- packages/reg-publish-gcs-plugin/src/gcs-publisher-plugin.ts
- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
- packages/reg-suit-util/src/cloud-storage-util.ts
Renamed a function, which has a strange name. It seems just a typo because there is an inconsistency between `fetchInternal` and `publishInteral`.
- I found this while trying to fix this issue #174 (I'm happy if you could check it too 😉)
No screenshots for this change.
I think it's ok not to check the behavior if you check the tsc compile succeed.
> fix: typo publishInteral to publishInternal

- packages/reg-publish-s3-plugin/README.md
Thank you for the useful tools. However, when I tried to use this tool, it took me a little time to decide what to do with AWS permissions information.
I think that there are many people who want to give only the necessary minimum authority, so I added the minimum authority information as far as I confirmed to the s3 plugin readme
If the information is incorrect, I would be happy to correct it.
> add iam policy doc to readme

- packages/reg-suit-cli/package.json
- yarn.lock
Upgrade `cp-file` to fix #163 .
This issue is caused by following points.
- `reg-cli` did not publish sample images.
It is already fixed by https://github.com/reg-viz/reg-suit/pull/164
- `cp-file`'s Node v10 compatibility issue.
ref: https://github.com/sindresorhus/cp-file/issues/25
- #163 
none
copy sample images
> fix: fixed a bug, sample image copying issue

- README.md
- packages/reg-suit-core/src/processor.ts
- packages/reg-suit-interface/src/core.ts
Added the flag `enableAntialias` to the core config, so that it's configurable if anti-aliased pixels are detected and ignored when comparing images, or not.
https://github.com/mapbox/pixelmatch/blob/38b395747e583e6932a13f80d17d4cb7a606c742/index.js#L60
> Add enableAntialias flag to core config

- packages/reg-notify-github-with-api-plugin/README.md
- packages/reg-notify-github-with-api-plugin/src/create-comment.ts
- packages/reg-notify-github-with-api-plugin/src/gh-api-notifier-plugin.ts
Adds a new option to `reg-notify-github-with-api-plugin` to show a smaller description in the comment.
- `shortDescription` - *Optional* Returns a small table with the item counts.
Example:
| 🔴 Changed | ⚪️ New | 🔵 Passing |
| ---        | ---    | ---        |
| 3          | 4      | 1420        |
This is useful when the number of items grows to a point where looking
at all the circles is no longer helpful and the body of the message
gets cut halfway through an HTML tag.
Before:
After:
> Option to show a small table instead of all the circles

- packages/reg-notify-gitlab-plugin/README.md
- packages/reg-notify-gitlab-plugin/src/gitlab-api-client.ts
- packages/reg-notify-gitlab-plugin/src/gitlab-notifier-plugin.ts
- packages/reg-notify-gitlab-plugin/src/testing/gitlab-fixture-client.ts
- packages/reg-notify-gitlab-plugin/src/use-cases.test.ts
- packages/reg-notify-gitlab-plugin/src/use-cases.ts
- packages/reg-notify-gitlab-plugin/test/fixtures/base-fulfilled/postMergeRequestDiscussion.json
- packages/reg-notify-gitlab-plugin/test/fixtures/base-no-marked-comment/postMergeRequestDiscussion.json
reg-notify-gitlab-plugin can select discussion comment type.
gitlab discussion api
https://docs.gitlab.com/ee/api/discussions.html#create-new-merge-request-thread
> add discussion to commentTo option

- packages/reg-notify-chatwork-plugin/.gitignore
- packages/reg-notify-chatwork-plugin/.npmignore
- packages/reg-notify-chatwork-plugin/README.md
- packages/reg-notify-chatwork-plugin/package.json
- packages/reg-notify-chatwork-plugin/src/chatwork-notifier-plugin.ts
- packages/reg-notify-chatwork-plugin/src/chatwork-preparer.ts
- packages/reg-notify-chatwork-plugin/src/index.ts
- packages/reg-notify-chatwork-plugin/src/send-web-hook.ts
- packages/reg-notify-chatwork-plugin/tsconfig.build.json
- packages/reg-notify-chatwork-plugin/tsconfig.json
- packages/reg-suit-cli/well-known-plugins.json
Allow push notification to Chatwork.com
Config chatwork-nofity:
```ts
{
chatworkToken:"xxxx-x-xxxxxx";
roomID:"123456789";
mrUrl:"$CI_MERGE_REQUEST_PROJECT_URL/-/merge_requests/$CI_MERGE_REQUEST_IID"; // for gitlab
mention:"[toall]";
pipelineUrl:  "$CI_PIPELINE_URL";
}
```
> Add plugin chatwork notify

- README.md
- packages/reg-suit-cli/src/cli-options.ts
- packages/reg-suit-cli/src/cli.ts
- packages/reg-suit-cli/src/package-util.ts
Add `--useYarnWs` for yarn workspace project.
I use `yarn workspace` in my project. When I introduce `reg-suit` to my project, `reg-suit init --useYarn` raise exception and fail to init.
This PR introduce  `useYarnWs` option for enable to generate `regconfig.json`.
- None
- None
Steps to reproduce
- git clone https://github.com/reg-viz/reg-suit.git
- cd reg-suit
- yarn
- yarn add -W -D reg-suit
- reg-suit init --useYarn
Result
```
[reg-suit] info version: 0.10.12                                                
? Plugin(s) to install (bold: recommended)  reg-keygen-git-hash-plugin : Detect 
the snapshot key to be compare with using Git hash.,  reg-notify-github-plugin :
Notify reg-suit result to GitHub repository,  reg-publish-s3-plugin : Fetch and
publish snapshot images to AWS S3. …
```
> Add yarn workspace option to reg-suit init

- packages/reg-notify-github-plugin/README.md
- packages/reg-notify-github-plugin/package.json
- packages/reg-notify-github-plugin/src/github-notifier-plugin.ts
- packages/reg-notify-github-plugin/src/github-preparer.ts
- yarn.lock
Add new option, `prCommentBehavior`,  for notifier-github-plugin . And it closes #364 .
> feat: Add prCommentBehavior option

- packages/reg-keygen-git-hash-plugin/src/git-cmd-client.ts
We are using Renovate, just like this project, to create pull requests for updating dependencies. Some of the branch names Renovate creates have parenthesis in them, e.g. `renovate/webpack-dependencies-(non-major)`. This causes issues when reg-suit is calling `git rev-parse` with the branch name, since it doesn't quote it. 
Error thrown:
```
/bin/sh: 1: Syntax error: "(" unexpected
Error: Command failed: git rev-parse renovate/webpack-dependencies-(non-major)
/bin/sh: 1: Syntax error: "(" unexpected
at checkExecSyncError (child_process.js:616:11)
at Object.execSync (child_process.js:652:15)
at GitCmdClient.revParse (/builds/frontend/packages/storybook/node_modules/reg-keygen-git-hash-plugin/lib/git-cmd-client.js:14:63)
at CommitExplorer.getCurrentCommitHash …
```
> fix: use quotes for parameter in 'git rev-parse'

- packages/reg-suit-cli/src/cli.ts
Fix minor typo in cli's help (see attached screenshot)
N/A
N/A
> Fix typo in sync-expected command

- packages/reg-notify-github-plugin/README.md
- packages/reg-notify-github-plugin/src/github-notifier-plugin.ts
I've ported the `reg-notify-github-with-api-plugin`'s `shortDescription` option to `reg-notify-github-plugin`.
Some checks will fail because `reg-gh-app-inteface` is not published yet. (I've confirmed these checks by overriding the dependency to my forked repository.)
- original PR: https://github.com/reg-viz/reg-suit/pull/207
- corresponding PR: https://github.com/reg-viz/gh-app/pull/60
- close: https://github.com/reg-viz/reg-suit/issues/566
- without `shortDescription`
- with `shortDescription`
> feat(reg-notify-github-plugin): support short description

- packages/reg-publish-s3-plugin/README.md
- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
AWS recommends disabling ACLs in S3, so add an option to use ACLs or not.
Default is to enable for backward compatibility.
- Disabling ACLs for all new buckets and enforcing Object Ownership - https://docs.aws.amazon.com/AmazonS3/latest/userguide/ensure-object-ownership.html
> Add enableACL option to s3-publisher-plugin

- packages/reg-notify-chatwork-plugin/package.json
- packages/reg-notify-chatwork-plugin/src/chatwork-notifier-plugin.ts
- packages/reg-notify-chatwork-plugin/src/chatwork-preparer.ts
- packages/reg-notify-chatwork-plugin/src/send-web-hook.ts
- packages/reg-notify-github-plugin/package.json
- packages/reg-notify-github-plugin/src/github-notifier-plugin.ts
- packages/reg-notify-github-with-api-plugin/package.json
- packages/reg-notify-github-with-api-plugin/src/gh-gql-client.ts
- packages/reg-notify-gitlab-plugin/package.json
- packages/reg-notify-gitlab-plugin/src/gitlab-api-client.ts
- packages/reg-notify-slack-plugin/package.json
- packages/reg-notify-slack-plugin/src/send-web-hook.ts
- packages/reg-notify-slack-plugin/src/slack-notifier-plugin.ts
- packages/reg-notify-slack-plugin/src/slack-preparer.ts
- packages/reg-suit-interface/src/plugin.ts
- yarn.lock
Since `request` and `request-promise` are deprecated long ago, I'm replacing them (and `node-fetch`) with `undici.fetch`
None
None, since this change should not affect UI.
Any behavior is not changed by this PR.
47dcd02 only includes optional refactoring. Feel free to revert it if you don't like destructuring arguments.
> Replace deprecated `request-promise` with `undici`

- packages/reg-notify-gitlab-plugin/README.md
- packages/reg-notify-gitlab-plugin/src/create-comment.ts
- packages/reg-notify-gitlab-plugin/src/gitlab-api-client.ts
- packages/reg-notify-gitlab-plugin/src/gitlab-notifier-plugin.ts
- packages/reg-notify-gitlab-plugin/src/use-cases.ts
This PR contains following changes:
- support `short description` option for the Gitlab Notifier
- fix 415 errors by missing `content-type` header for Gitlab REST API (closes #621)
- predecessor PR: https://github.com/reg-viz/reg-suit/pull/558
- almost same my prior PR for the Github Notifier: https://github.com/reg-viz/reg-suit/pull/575
> feat(reg-notify-gitlab-plugin): support short description

- packages/reg-publish-s3-plugin/e2e/script.ts
- packages/reg-publish-s3-plugin/package.json
- packages/reg-publish-s3-plugin/src/s3-bucket-preparer.ts
- packages/reg-publish-s3-plugin/src/s3-publisher-plugin.ts
- yarn.lock
Moves from `aws-sdk` v2 (deprecated) to `@aws-sdk` v3.
- Would close #622 
Should create buckets, put and pull files just as it used to.
> Upgrade to @aws-sdk v3

- packages/reg-publish-s3-plugin/README.md
The S3 actions does not have s3:ListObject, and the s3:ListBucket is required to run ListObjects.
[Actions defined by Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/list_amazons3.html#amazons3-actions-as-permissions)
> docs: Modify the reg-publish-s3-plugin README to use s3:ListBucket instead of s3:ListObject

- README.md
- packages/reg-suit-core/src/processor.ts
- packages/reg-suit-interface/src/core.ts
In `compare` command, reg-suit uses [reg-cli](https://github.com/reg-viz/reg-cli).
reg-cli provides `concurrency` option, but we couldn't set this option from reg-suit.
I added `concurrency` option to the "core" section of config.
- reg-cli Options: https://github.com/reg-viz/reg-cli?tab=readme-ov-file#options
> feat: add concurrency option for comparaison

- packages/reg-notify-github-with-api-plugin/src/create-comment.ts
This change addresses an issue where the `short description` in `reg-notify-github-with-api-plugin` was not being properly rendered in the PR comments. I have fixed it to ensure it displays correctly as Markdown.
I referenced a similar fix made in `reg-notify-gitlab-plugin` to guide this implementation.
- https://github.com/reg-viz/reg-suit/pull/625
- It seems related to this issue: https://github.com/reg-viz/reg-suit/issues/626
In my project, the comments were being displayed like this with the current package:
> fix(reg-notify-github-with-api-plugin): fix short description style

- packages/reg-suit-core/src/processor.ts
I'm using own Slack Notify plugin and we want to notify `expectedKey` through it. However, currently in the `syncExpected` function in reg-suit-core, it's not passing the `ctx` argument, causing expectedKey to be lost. Therefore, I modified `syncExpected` to include the contents of the `ctx` argument in its return value.
(I thought it would be appropriate to inherit the contents of `ctx` because the return type is also `StepResultAfterExpectedKey`.)
nothing
nothing
I have enabled any Publisher plugin and executed run with the --verbose flag. I checked the `"expectedKey"` log output and confirmed that it was displayed in the form of `"Notify parameters:"`.
> fix: pass expectedKey after syncExpected
